version: '3.7'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./pgdata:/data:delegated"
    environment:
      PGPORT:            5432
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"